
---
- name: check_error_and_ignore_error
  hosts: STAGING_SERVERS_01, STAGING_SERVERS_02
#  any_errors_fatal: true
  become: yes


  tasks:
  - name: Task Number 1
    apt: name=treeeee state=present
#    ignore_errors: yes

  - name: Task Number 2
    shell: echo hello World!
    register: results
#    failed_when: results.rc == 0
#    failed_when: "'World' in results.stdout"

  - debug:
      var: results

  - name: Task Number 3
    shell: echo Hellomir!
