---
- name: Loops Playbook
  hosts: [STAGING_SERVERS_01]
  become: yes

  tasks:
  - name: Say Hello to all Servers
    debug: msg="Hello {{ item }}"
    loop:
        - "Alexander"
        - "Valera"
        - "Petya"

  - name: Loop Until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZ") == false

  - name: Print Final Output
    debug:
      var: output.stdout

  - name: Install many packets
    apt: name={{ item }} state=present
    with_items:
          - screen
